<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jfom"
    nsURI="http://www.earthsystemcurator.org/jfom" nsPrefix="jfom">
  <eClassifiers xsi:type="ecore:EEnum" name="AccessSpec">
    <eLiterals name="public" literal="public"/>
    <eLiterals name="private" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccessStatement" eSuperTypes="#//SpecificationStatement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessSpec" lowerBound="1"
        eType="#//AccessSpec"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessIdentifier" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionStatement" abstract="true" eSuperTypes="#//ExecutableConstruct"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActualArgumentSpec" eSuperTypes="#//StringTemplateAdapter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argument" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArbitraryTextConstruct" eSuperTypes="#//ExecutableConstruct">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayConstructor" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrayConstructorValue"
        lowerBound="1" upperBound="-1" eType="#//ArrayConstructorValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayConstructorValue" abstract="true"
      interface="true" eSuperTypes="#//StringTemplateAdapter"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssignmentStatement" eSuperTypes="#//ActionStatement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variable" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrSpec" abstract="true" eSuperTypes="#//StringTemplateAdapter"/>
  <eClassifiers xsi:type="ecore:EClass" name="CallStatement" eSuperTypes="#//ActionStatement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subroutineName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actualArgument" upperBound="-1"
        eType="#//ActualArgumentSpec" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContainsStatement" eSuperTypes="#//StringTemplateAdapter"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeclarationConstruct" eSuperTypes="#//StringTemplateAdapter"/>
  <eClassifiers xsi:type="ecore:EClass" name="DerivedTypeSpec" eSuperTypes="#//TypeSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoConstruct" eSuperTypes="#//ExecutableConstruct">
    <eOperations name="setStart" lowerBound="1">
      <eParameters name="start" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="setEnd" lowerBound="1">
      <eParameters name="end" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doVariable" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionPartConstruct"
        upperBound="-1" eType="#//ExecutionPartConstruct" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndModuleStatement" eSuperTypes="#//StringTemplateAdapter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="moduleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndProgramStatement" eSuperTypes="#//StringTemplateAdapter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="programName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndSubroutineStatement" eSuperTypes="#//StringTemplateAdapter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subroutineName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EStringTemplate" instanceClassName="org.antlr.stringtemplate.StringTemplate"
      abstract="true" interface="true" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EDataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutableConstruct" abstract="true"
      eSuperTypes="#//ExecutionPartConstruct"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionPart" eSuperTypes="#//StringTemplateAdapter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionPartConstruct"
        upperBound="-1" eType="#//ExecutionPartConstruct" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionPartConstruct" eSuperTypes="#//StringTemplateAdapter"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//ArrayConstructorValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionReference" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actualArgument" upperBound="-1"
        eType="#//ActualArgumentSpec" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionSubprogram" eSuperTypes="#//ModuleSubprogram"/>
  <eClassifiers xsi:type="ecore:EClass" name="IfStatement" eSuperTypes="#//ActionStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//ActionStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImplicitPart" eSuperTypes="#//StringTemplateAdapter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitPartStatement"
        lowerBound="1" upperBound="-1" eType="#//ImplicitPartStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImplicitPartStatement" eSuperTypes="#//StringTemplateAdapter"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImplicitStatement" eSuperTypes="#//ImplicitPartStatement">
    <eOperations name="isNone" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitSpecList" lowerBound="1"
        transient="true">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntentAttrSpec" eSuperTypes="#//AttrSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intentSpec" lowerBound="1"
        eType="#//IntentSpec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IntentSpec">
    <eLiterals name="in"/>
    <eLiterals name="out" value="1"/>
    <eLiterals name="inout" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalSubprogramPart"/>
  <eClassifiers xsi:type="ecore:EEnum" name="IntrinsicType">
    <eLiterals name="integer"/>
    <eLiterals name="real" value="1"/>
    <eLiterals name="doublePrecision" value="2"/>
    <eLiterals name="complex" value="3"/>
    <eLiterals name="character" value="4"/>
    <eLiterals name="logical" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntrinsicTypeSpec" eSuperTypes="#//TypeSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//IntrinsicType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralConstant" eSuperTypes="#//Constant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MainProgram" eSuperTypes="#//ProgramUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="programStatement" lowerBound="1"
        eType="#//ProgramStatement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specificationPart" eType="#//SpecificationPart"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionPart" eType="#//ExecutionPart"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalSubprogramPart"
        eType="#//InternalSubprogramPart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endProgramStatement" lowerBound="1"
        eType="#//EndProgramStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="#//ProgramUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="moduleStatement" lowerBound="1"
        eType="#//ModuleStatement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specificationPart" eType="#//SpecificationPart"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moduleSubprogramPart" lowerBound="1"
        eType="#//ModuleSubprogramPart" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endModuleStatement" lowerBound="1"
        eType="#//EndModuleStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleStatement" eSuperTypes="#//StringTemplateAdapter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="moduleName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleSubprogram" abstract="true" eSuperTypes="#//StringTemplateAdapter"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleSubprogramPart" eSuperTypes="#//StringTemplateAdapter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsStatement" lowerBound="1"
        eType="#//ContainsStatement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moduleSubprogram" lowerBound="1"
        upperBound="-1" eType="#//ModuleSubprogram" derived="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedConstant" eSuperTypes="#//Constant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrintStatement" eSuperTypes="#//ActionStatement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputItem" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProgramUnit" abstract="true" eSuperTypes="#//StringTemplateAdapter"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProgramStatement" eSuperTypes="#//StringTemplateAdapter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="programName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SaveAttrSpec" eSuperTypes="#//AttrSpec"/>
  <eClassifiers xsi:type="ecore:EClass" name="SpecificationPart" eSuperTypes="#//StringTemplateAdapter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="useStatement" upperBound="-1"
        eType="#//UseStatement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitPart" eType="#//ImplicitPart"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarationConstruct" upperBound="-1"
        eType="#//DeclarationConstruct" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecificationStatement" abstract="true"
      eSuperTypes="#//DeclarationConstruct"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringTemplateAdapter" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stringTemplate" lowerBound="1"
        eType="#//EStringTemplate" changeable="false" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubroutineStatement" eSuperTypes="#//StringTemplateAdapter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subroutineName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formalArgument" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubroutineSubprogram" eSuperTypes="#//ModuleSubprogram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subroutineStatement" lowerBound="1"
        eType="#//SubroutineStatement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specificationPart" eType="#//SpecificationPart"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionPart" eType="#//ExecutionPart"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalSubprogramPart"
        eType="#//InternalSubprogramPart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endSubroutineStatement"
        lowerBound="1" eType="#//EndSubroutineStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDeclarationStatement" eSuperTypes="#//DeclarationConstruct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeSpec" lowerBound="1"
        eType="#//TypeSpec" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attrSpec" upperBound="-1"
        eType="#//AttrSpec" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entityDeclaration" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeSpec" abstract="true" eSuperTypes="#//StringTemplateAdapter"/>
  <eClassifiers xsi:type="ecore:EClass" name="UseStatement" eSuperTypes="#//StringTemplateAdapter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="moduleName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="renameList" lowerBound="1"
        transient="true">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="_Spacer" eSuperTypes="#//ExecutionPartConstruct"/>
</ecore:EPackage>
